[project]
name = "mypackage"
version = "0.1.0"
dependencies = [
    # To read Toml
    "tomli",
    # To check if file is image
    "filetype"
]

[project.scripts]
gallery = "gallery:main"

[pytest]
testpaths = "test"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"